### ISSUE TITLE
export all types from reply

### ISSUE THREAD

**Issue by archaeron** [meraymond2/idris-ide-client#3]
for me to use the types in the atom ide mode I'd love to have the types you've defined in the `reply.ts` file.

Preferably the nested types would be split up too.
Maybe something similar to this?
```
  export type Metavariables = {
    ok: {
      metavariable: {
        name: string
        type: string
        metadata: MessageMetadata[]
      }
      scope: {
        name: string
        type: string
        metadata: MessageMetadata[]
      }[]
    }[]
    id: number
    type: ":return"
  }
```
->
```
type  Metavariables = {
    ok: Array<Metavariable>
    id: number
    type: ":return"
  }

type Metavariable = {
   metavariable: Variable
   scope: Array<HolePremise>
}

type Variable = {
   name: string
   type: string
   metadata: Array<MessageMetadata>
}

type HolePremise = {
   name: string
   type: string
   metadata: Array<MessageMetadata>
}
```
names from:
https://github.com/idris-lang/Idris2/blob/97366f022df7ceaab832b1aa8371a2f17334c745/src/Idris/IDEMode/Holes.idr

**Comment by meraymond2** [comment]
Sounds good :+1:

Should also make sure any types used in the replies are re-exported. I ran into a few types I wanted to access in the vs plugin that I had to import from the sub directories, and it doesn't look as nice.
